# SPDX-FileCopyrightText: 2024 AerynOS Developers
# SPDX-License-Identifier: MPL-2.0

---
name: Package Lint
on:
  pull_request:
    paths-ignore:
      - 'tools/**'
      - 'releases/**'
      - 'typos/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  Recipes:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - run: |
        sudo apt-get update
        sudo apt-get install python3-ruamel.yaml
        tools/CI/package_checks.py --base=origin/${{ github.event.pull_request.base.ref }}
  Repository:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Verify REUSE compliance
        uses: fsfe/reuse-action@v6.0.0
        continue-on-error: true
